
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Jabatan;
import model.Pegawai;

/*
 * Tugas java
 *
 * Created on 30 Mei 2021
 */

/**
 *
 * @author  diva
 */
public class JFramePraktek14 extends JFrame {
    
    private Pegawai pegawai;
    
    /** Creates new form JFramePraktek14 */
    public JFramePraktek14() {
        initComponents();
        radioGroup.add(radioButtonMenikah);
        radioGroup.add(radioButtonBelumMenikah);
    }
    
    private void setStatusMenikah(boolean status) {
        
        // check if pegawai is null
        if (pegawai == null) {
            radioGroup.clearSelection();
            JOptionPane.showMessageDialog(rootPane, "Mohon pilih jabatan terlebih dahulu!");
            return;
        }
        
        // update pegawai jumlah anak
        int jumlahAnak = Integer.parseInt(textFieldJumlahAnak.getText());
        pegawai.setJumlahAnak(jumlahAnak);
        
        // update pegawai status menikah
        pegawai.setStatusMenikah(status);
        
        // enable text field jumlah anak
        textFieldJumlahAnak.setEditable(status);
        
        // hapus data output lama
        textFieldGajiKotor.setText("Rp. 0");
        textFieldPajak.setText("Rp. 0");
        textFieldGajiBersih.setText("Rp. 0");
        
        // tampilkan output data
        calculateOutput();
    }
    
    private void calculateOutput() {
        textFieldJumlahAnak.setText(String.format("%d", pegawai.getJumlahAnak()));
        textFieldTunjanganAnak.setText(String.format("Rp. %d", pegawai.getTunjanganAnak()));
        textFieldTunjanganIstri.setText(String.format("Rp. %d", pegawai.getTunjanganIstri()));
    }
    
    private void calculateTotal() {
        int gajiBersih = pegawai.getGajiPokok() + pegawai.getTunjanganAnak() + pegawai.getTunjanganIstri();
        int pajak = pegawai.getPajak();
        textFieldGajiKotor.setText(String.format("Rp. %d", gajiBersih));
        textFieldPajak.setText(String.format("Rp. %d", pajak));
        textFieldGajiBersih.setText(String.format("Rp. %d", gajiBersih - pajak));
    }
    
    private void clearOutput() {
        pegawai = null;
        textFieldGajiPokok.setText("Rp. 0");
        textFieldJumlahAnak.setText("0");
        textFieldTunjanganAnak.setText("Rp. 0");
        textFieldTunjanganIstri.setText("Rp. 0");
        textFieldGajiKotor.setText("Rp. 0");
        textFieldPajak.setText("Rp. 0");
        textFieldGajiBersih.setText("Rp. 0");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldNIP = new javax.swing.JTextField();
        textFieldName = new javax.swing.JTextField();
        comboBoxJabatan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        radioButtonMenikah = new javax.swing.JRadioButton();
        radioButtonBelumMenikah = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        textFieldGajiPokok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldTunjanganIstri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldJumlahAnak = new javax.swing.JTextField();
        textFieldTunjanganAnak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldGajiKotor = new javax.swing.JTextField();
        buttonHitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textFieldPajak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldGajiBersih = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonBersih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIP");

        jLabel2.setText("Nama");

        jLabel3.setText("Jabatan");

        comboBoxJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jabatan", "Direktur", "Manajer", "Kabag", "Sekretaris", "Karyawan", "Office Boy" }));
        comboBoxJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxJabatanActionPerformed(evt);
            }
        });

        jLabel4.setText("Gaji Pokok");

        radioButtonMenikah.setText("Menikah");
        radioButtonMenikah.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonMenikah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMenikahActionPerformed(evt);
            }
        });

        radioButtonBelumMenikah.setText("Belum Menikah");
        radioButtonBelumMenikah.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioButtonBelumMenikah.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonBelumMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonBelumMenikahActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        textFieldGajiPokok.setEditable(false);
        textFieldGajiPokok.setText("Rp. 0");

        jLabel6.setText("Tunjangan Istri (20% Gaji)");

        textFieldTunjanganIstri.setEditable(false);
        textFieldTunjanganIstri.setText("Rp. 0");
        textFieldTunjanganIstri.setToolTipText("");

        jLabel7.setText("Jumlah Anak");

        jLabel8.setText("Tunjangan Anak (15% Gaji)");

        textFieldJumlahAnak.setEditable(false);
        textFieldJumlahAnak.setText("0");
        textFieldJumlahAnak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldJumlahAnakKeyReleased(evt);
            }
        });

        textFieldTunjanganAnak.setEditable(false);
        textFieldTunjanganAnak.setText("Rp. 0");

        jLabel9.setText("Gaji Kotor");

        textFieldGajiKotor.setEditable(false);
        textFieldGajiKotor.setText("Rp. 0");

        buttonHitung.setText("Hitung");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        jLabel10.setText("Pajak (10% Gaji)");

        textFieldPajak.setEditable(false);
        textFieldPajak.setText("Rp. 0");

        jLabel11.setText("Gaji Bersih");

        textFieldGajiBersih.setEditable(false);
        textFieldGajiBersih.setText("Rp. 0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Perhitungan Gaji PT DIVA");

        buttonBersih.setText("Bersih");
        buttonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldGajiKotor)
                                    .addComponent(textFieldPajak)
                                    .addComponent(textFieldGajiBersih)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textFieldNIP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboBoxJabatan, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                        .addComponent(textFieldGajiPokok, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(radioButtonMenikah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioButtonBelumMenikah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldTunjanganAnak, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(textFieldJumlahAnak)
                                    .addComponent(textFieldTunjanganIstri))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonBersih)
                                .addGap(13, 13, 13)
                                .addComponent(buttonHitung)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(98, 98, 98))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonMenikah, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonBelumMenikah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldJumlahAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTunjanganAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTunjanganIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldGajiKotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldGajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBersih)
                    .addComponent(buttonHitung))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldJumlahAnakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldJumlahAnakKeyReleased
        setStatusMenikah(true);
    }//GEN-LAST:event_textFieldJumlahAnakKeyReleased

    private void comboBoxJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxJabatanActionPerformed
        if (comboBoxJabatan.getSelectedIndex() != 0) {
            if (textFieldNIP.getText().isEmpty()) {
                comboBoxJabatan.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "Mohon isi NIP Anda!");
                return;
            }
            if (textFieldName.getText().isEmpty()) {
                comboBoxJabatan.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "Mohon isi nama Anda!");
                return;
            }
            String nip = textFieldNIP.getText();
            String name = textFieldName.getText();
            Jabatan jabatan = new Jabatan(String.valueOf(comboBoxJabatan.getSelectedItem()));
            pegawai = new Pegawai(nip, name, jabatan);
            textFieldGajiPokok.setText(String.format("Rp. %d", pegawai.getGajiPokok()));
            radioGroup.clearSelection();
            textFieldJumlahAnak.setEditable(false);
            textFieldJumlahAnak.setText("0");
            textFieldTunjanganIstri.setText("Rp. 0");
        } else {
            clearOutput();
        }
    }//GEN-LAST:event_comboBoxJabatanActionPerformed

    private void radioButtonBelumMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonBelumMenikahActionPerformed
        setStatusMenikah(false);
    }//GEN-LAST:event_radioButtonBelumMenikahActionPerformed

    private void radioButtonMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMenikahActionPerformed
        setStatusMenikah(true);
    }//GEN-LAST:event_radioButtonMenikahActionPerformed

    private void buttonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihActionPerformed
        textFieldNIP.setText("");
        textFieldName.setText("");
        clearOutput();
    }//GEN-LAST:event_buttonBersihActionPerformed

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        
        // check if pegawai is null
        if (pegawai == null) {
            radioGroup.clearSelection();
            JOptionPane.showMessageDialog(rootPane, "Mohon pilih jabatan terlebih dahulu!");
            return;
        }
        
        // tampilkan output data total
        calculateTotal();
    }//GEN-LAST:event_buttonHitungActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                JFrame jFrame = new JFramePraktek14();
                jFrame.setTitle("Aplikasi Perhitungan Gaji");
                jFrame.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JComboBox comboBoxJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioButtonBelumMenikah;
    private javax.swing.JRadioButton radioButtonMenikah;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JTextField textFieldGajiBersih;
    private javax.swing.JTextField textFieldGajiKotor;
    private javax.swing.JTextField textFieldGajiPokok;
    private javax.swing.JTextField textFieldJumlahAnak;
    private javax.swing.JTextField textFieldNIP;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPajak;
    private javax.swing.JTextField textFieldTunjanganAnak;
    private javax.swing.JTextField textFieldTunjanganIstri;
    // End of variables declaration//GEN-END:variables
}